### ISSUE TITLE
install on turnkey lamp under proxmox

### ISSUE THREAD

**Issue by roswitina** [canlot/LZMWeb#1]
I would like the program in turnkey lamp (Proxmox - container) install?
is that possible? If so, what steps are necessary?

**Comment by canlot** [comment]
I don't know. Maybe it will be in future. But the application is not ready yet, it is still in development.
If you want, you can contribute to.

**Comment by roswitina** [comment]
I think that is too high to me. I am a better users individual. Thanks.
